export interface Ad {
  id: string,
  tipo: string,
  nombre: string,
  descripcion: string,
  imagenes: string[],
  calle: string,
  ciudad: string,
  busqueda: string,
  precio: string,
  m2: Number,
  planta: Number,
  habitaciones: Number,
  baños: Number,
  caracteristicas: {
    tipoInmueble: string,
    aguaCaliente: string,
    estado: string,
    ascensor: Boolean,
    consumoEnergetico: string,
    emisiones: string,
    parking: string,
    antigüedad: string,
    amueblado: Boolean,
    calefaccion: string,
    orientacion: string
  },
  extra: string[],
  inmobiliaria: string,
  imagenInmobiliaria: string,
  telefono: Number,
  email: string,
}
