export interface Ad {
  id: string,
  tipo: String,
  nombre: string,
  descripcion: string,
  imagenes: String[],
  calle: String,
  ciudad: string,
  busqueda: String,
  precio: string,
  m2: Number,
  planta: Number,
  habitaciones: Number,
  baños: Number,
  caracteristicas: {
    tipoInmueble: String,
    aguaCaliente: String,
    estado: String,
    ascensor: Boolean,
    consumoEnergetico: String,
    emisiones: String,
    parking: String,
    antigüedad: String,
    amueblado: Boolean,
    calefaccion: String,
    orientacion: String
  },
  extra: String[],
  inmobiliaria: String,
  imagenInmobiliaria: String,
  telefono: Number,
  email: String,
}
