POST http://localhost:3001/api/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDIzMjY1ZGIyN2E2NjEwOTExNjkzYTAiLCJpYXQiOjE2ODAwMjU0MjN9.4OKkIyYIa65TpbJaPfLcjsLY2dyJCp5QYshXufm82Bo

{
  "username": "test4",
  "password": "testingaa"
}