PUT http://localhost:3001/api/viviendas/5f9b9b0b0b9b9b0b0b9b9b0b
Content-Type: application/json
{
  "tipo": "piso",
  "nombre": "Pisooooo",
  "descripcion": "Pisoooooo en venta en calle de la paz",
  "imagenes": [],
  "calle": "Calle de la paz",
  "ciudad": "Madrid",
  "precio": 100000,
  "m2": 100,
  "planta": 1,
  "habitaciones": 3,
  "baños": 2,
  "caracteristicas": {
    "tipoInmueble": "Piso",
    "aguaCaliente": "Individual",
    "estado": "Para reformar",
    "ascensor": true,
    "consumoEnergetico": "E",
    "emisiones": "E"
  },
  "extra": ["Amueblado", "Trastero", "Terraza"],
  "inmobiliaria": "Inmobiliaria 1",
  "imagenInmobiliaria": "https://picsum.photos/200/300",
  "telefono": 123456789,
  "email": "prueba@gmail.com"
}