PUT http://localhost:3001/api/viviendas/63d8008ae10623f3bf7b6dba
Content-Type: application/json

   {
    "caracteristicas": {
      "tipoInmueble": "Piso",
      "aguaCaliente": "",
      "estado": "",
      "ascensor": true,
      "consumoEnergetico": "D",
      "emisiones": "D",
      "parking": "Privado"
    },
    "tipo": "comprar",
    "nombre": "Piso en venta en Jose Flores Camara, Ciudad Jardín - Zoco",
    "descripcion": "En el Zoco, a un lado el Centro Comercial y al otro el centro deportivo Forus (Poniente) y situado en una tranquila calle peatonal (Pasaje José Flores Cámara) encontrarás un coqueto piso justo como tú querías.Se trata de una 3º planta con ascensor en uno de los edificios más emblemáticos de la zona, Edificio Danubio, construido con altísimas calidades por la empresa Angel Tirado, calidades que se pueden observar y disfrutar hoy en día: suelo de mármol, cierres de climalit con rotura de puente térmico, persianas eléctricas, pasillos de mármol y granito, enormes zonas comunes con patio infantil y gran fuente..",
    "imagenes": [
      "https://static.inmofactory.com/images/inmofactory/documents/1/112153/32903045/544532555.jpg?rule=web_1200x0",
      "https://static.inmofactory.com/images/inmofactory/documents/1/112153/32903045/544532556.jpg?rule=web_1200x0",
      "https://static.inmofactory.com/images/inmofactory/documents/1/112153/32903045/544532557.jpg?rule=web_1200x0",
      "https://static.inmofactory.com/images/inmofactory/documents/1/112153/32903045/544532558.jpg?rule=web_1200x0",
      "https://static.inmofactory.com/images/inmofactory/documents/1/112153/32903045/544532559.jpg?rule=web_1200x0",
      "https://static.inmofactory.com/images/inmofactory/documents/1/112153/32903045/544532560.jpg?rule=web_1200x0"
    ],
    "calle": "Jose Flores Camara, Ciudad Jardín - Zoco",
    "ciudad": "Córdoba",
    "busqueda": "cordoba",
    "precio": 175000,
    "m2": 74,
    "planta": 3,
    "habitaciones": 2,
    "baños": 1,
    "extra": [
      "Aire acondicionado",
      "Armarios",
      "Parque",
      "Terraza",
      "Trastero",
      "Electrodomésticos",
      "Balcón",
      "Videoportero",
      "Cocina Equipada"
    ],
    "inmobiliaria": "RK CASAS PARA VIVIR",
    "imagenInmobiliaria": "https://static.fotocasa.es/images/client/9a9b03ae-5a5d-4793-8a20-6fc6d97feb50/20221201091102.jpeg?rule=web_100x52",
    "telefono": 123456789,
    "email": "prueba@gmail.com",
    "id": "63d8008ae10623f3bf7b6dba"
  }